apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - backend.yaml
  - frontend.yaml
  - backend-servicemonitor.yaml

configMapGenerator:
  - name: backend-dashboard
    files:
      - monitoring/dashboards/backend.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
